# Generated by Django 4.2.2 on 2023-07-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_profile_email_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
