# Generated by Django 4.2.2 on 2023-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_remove_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
