# Generated by Django 4.2.2 on 2023-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_profile_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(default='', max_length=254)),
                ('company_avatar', models.ImageField(upload_to='company_logo/')),
            ],
        ),
    ]
