# Generated by Django 4.2.2 on 2023-07-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_computer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='user',
        ),
        migrations.AddField(
            model_name='computer',
            name='responsible',
            field=models.CharField(default='', max_length=255),
        ),
    ]
