# Generated by Django 4.2.2 on 2023-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_rename_microprocesor_brand_computer_microprocessor_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
